services:

    sylius.google_tag_manager.enhanced_ecommerce_tracking.listener.cart.abstract:
        class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\EventListener\CartListener
        abstract: true
        arguments:
            - "@sylius.context.cart"
            - '@sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.cart'

    sylius.google_tag_manager.enhanced_ecommerce_tracking.listener.checkout_step.abstract:
        class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\EventListener\CheckoutStepListener
        abstract: true
        arguments:
            - "@sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.checkout_step"
            - "@sylius.context.cart"
