services:

  sylius.google_tag_manager.enhanced_ecommerce_tracking.add_shipping_info:
    parent: sylius.google_tag_manager.enhanced_ecommerce_tracking.listener.checkout_step.abstract
    arguments:
      - !php/const StefanDoorn\SyliusGtmEnhancedEcommercePlugin\TagManager\CheckoutStepInterface::STEP_SHIPPING
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
