services:

  sylius.google_tag_manager.enhanced_ecommerce_tracking.begin_checkout:
    parent: sylius.google_tag_manager.enhanced_ecommerce_tracking.listener.checkout_step.abstract
    arguments:
      - !php/const Sylius\Component\Core\OrderCheckoutStates::STATE_ADDRESSED
    tags:
      - name: kernel.event_listener
        event: sylius.order.post_address
