services:

  sylius.google_tag_manager.enhanced_ecommerce_tracking.purchase:
    class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\EventListener\ThankYouListener
    arguments:
      - "@sylius.repository.order"
      - "@sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.checkout_step"
    tags:
      - name: kernel.event_listener
        event: kernel.controller
