services:

  sylius.google_tag_manager.enhanced_ecommerce_tracking.cart.listener.remove_from_cart:
    parent: sylius.google_tag_manager.enhanced_ecommerce_tracking.listener.cart.abstract
    tags:
      - name: kernel.event_listener
        event: !php/const Sylius\Component\Order\SyliusCartEvents::CART_ITEM_REMOVE
        method: onRemoveFromCart
