services:

  sylius.google_tag_manager.enhanced_ecommerce_tracking.view_item_list.listener:
    class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\EventListener\ViewItemListListener
    arguments:
      - "@sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.view_item_list"
    tags:
      - { name: kernel.event_listener, event: sylius.taxon.show }
