imports:
    - { resource: "services/*.yaml" }

services:

    sylius.google_tag_manager.enhanced_ecommerce_tracking.resolver.checkout_step:
        class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\Resolver\CheckoutStepResolver

    sylius.google_tag_manager.enhanced_ecommerce_tracking.helper.product_identifier:
        class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\Helper\ProductIdentifierHelper
        arguments:
            - "%sylius_gtm_enhanced_ecommerce.product_identifier%"
