imports:
    - { resource: "services/*.yaml" }

services:

    sylius.google_tag_manager.enhanced_ecommerce_tracking.resolver.checkout_step:
        class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\Resolver\CheckoutStepResolver

    sylius.google_tag_manager.enhanced_ecommerce_tracking.helper.product_identifier:
        class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\Helper\ProductIdentifierHelper
        arguments:
            - "%sylius_gtm_enhanced_ecommerce.product_identifier%"

    sylius.google_tag_manager.enhanced_ecommerce_tracking.service.cached_google_tag_manager:
        class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\Service\CachedGoogleTagManager
        decorates: google_tag_manager
        arguments:
            - "@.inner"
            - '@cache.sylius_gtm_enhanced_ecommerce'
        tags:
            - name: kernel.event_listener
              event: !php/const Symfony\Component\HttpKernel\KernelEvents::TERMINATE
              method: reset
